services:
  adguard:
    container_name: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 4443:443/tcp
      - 4443:443/udp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
    restart: unless-stopped
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    image: adguard/adguardhome
    networks:
      - proxy_network
    depends_on:
      - unbound

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    networks:
      proxy_network:
        ipv4_address: 172.18.0.250
    
networks:
  proxy_network:
    external: true
