server:
    verbosity: 1
    # Écoute sur toutes les interfaces
    interface: 0.0.0.0
    port: 53
    
    # Autoriser les requêtes depuis ton réseau local et Docker
    access-control: 127.0.0.0/8 allow
    access-control: 172.0.0.0/8 allow
    access-control: 192.168.1.0/24 allow

    # Paramètres de sécurité et vie privée
    hide-identity: yes
    hide-version: yes
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    
    # Mise en cache
    cache-min-ttl: 300
    cache-max-ttl: 86400
    
    # Root hints pour la résolution récursive
    root-hints: "/opt/unbound/etc/unbound/root.hints"

    username: ""
    chroot: ""

remote-control:
    control-enable: no