services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    networks:
      - proxy_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.rule=Host(`it-tools.azby.fr`)
      - traefik.http.routers.it-tools.entrypoints=websecure
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.routers.it-tools.tls.certresolver=ovh
      - traefik.http.services.it-tools.loadbalancer.server.port=80

networks:
  proxy_network:
    external: true