all:
  hosts:
    debian-13-vierge:
      ansible_host: 192.168.1.53
      ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      ansible_ssh_private_key_file: ~/.ssh/id_25519_ansible
      ansible_user: root
    debian-13-vierge-2:
      ansible_host: 192.168.1.68
      ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      ansible_ssh_private_key_file: ~/.ssh/id_25519_ansible
      ansible_user: root
