---
# ==============================================================================
# BLOC 1 : Restauration ou provisionnement Proxmox (Localhost)
# ==============================================================================
- name: "Vérification et Restauration Proxmox"
  hosts: localhost
  gather_facts: false
  vars_files:
    - config.yml
  tasks: # Utiliser tasks au lieu de role permet de rajouter d'autres tâches aux besoins
    - name: "Restauration des LXC"
      ansible.builtin.include_role:
        name: proxmox_restore

# ==============================================================================
# BLOC 2 : Configuration de Base du Système (Tous les LXC)
# ==============================================================================
- name: "Configuration de base des conteneurs"
  hosts: all
  gather_facts: true
  vars_files:
    - config.yml
  roles:
    - common

# ==============================================================================
# BLOC 3 : Déploiement des Applications Spécifiques (Cible par hôte)
# ==============================================================================
- name: "Déploiement de Grafana"
  hosts: grafana-test-iac
  vars_files:
    - config.yml
  roles:
    - grafana

# ==============================================================================
# BLOC 4 : Déploiement de la base de données de métriques
# ==============================================================================
- name: "Déploiement de VictoriaMetrics"
  hosts: victoria-metrics-test-iac
  gather_facts: true
  vars_files:
    - config.yml
  roles:
    - victoria_metrics

# ==============================================================================
# BLOC 5 : Déploiement de nginx proxy manager
# ==============================================================================
- name: "Déploiement de Nginx Proxy Manager"
  hosts: nginx-proxy-manager-test-iac
  gather_facts: true
  vars_files:
    - config.yml
  roles:
    - nginx_proxy_manager