---
# ==============================================================================
# BLOC 1 : Restauration ou provisionnement Proxmox (Localhost)
# ==============================================================================
- name: "Vérification et Restauration Proxmox"
  hosts: localhost
  gather_facts: false
  vars_files:
    - hosts.yml
  tasks:
    - name: "Restauration des LXC"
      ansible.builtin.include_role:
        name: proxmox_restore
      when: terraform_ran | bool

# ==============================================================================
# BLOC 2 : Configuration de Base du Système (Tous les LXC)
# ==============================================================================
- name: "Configuration de base des conteneurs"
  hosts: all
  gather_facts: true
  vars_files:
    - hosts.yml
  roles:
    - role: common
      when: terraform_ran | bool

# ==============================================================================
# BLOC 3 : Créer le container lxc avec docker
# ==============================================================================
- name: Déployer Docker sur le conteneur LXC
  hosts: docker_hosts
  become: true
  vars_files:
    - hosts.yml
  roles:
    - docker

# ==============================================================================
# BLOC 4 : Déployer Tailscale
# ==============================================================================
- name: Déployer Tailscale
  hosts: docker_hosts
  become: true
  vars_files:
    - hosts.yml
  roles:
    - tailscale