---
# vars file for roles/grafana

# Configuration réseau de Grafana
grafana_port: 3000
grafana_bind_address: "0.0.0.0"

# Sécurité (Compte Administrateur par défaut)
grafana_admin_user: "admin"
grafana_admin_password: "MonMotDePasseSuperSecurise123!"

# Configuration de la base de données interne (SQLite par défaut)
grafana_db_type: "sqlite3"

# Fonctionnalités à activer/désactiver
grafana_analytics_enabled: false
grafana_allow_sign_up: false  # Interdit aux inconnus de créer un compte