---
# tasks file for roles/victoria_metrics

- name: "VictoriaMetrics : Créer le groupe système"
  ansible.builtin.group:
    name: victoriametrics
    system: yes
    state: present

- name: "VictoriaMetrics : Créer l'utilisateur système"
  ansible.builtin.user:
    name: victoriametrics
    group: victoriametrics
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
    state: present

- name: "VictoriaMetrics : Créer les dossiers de configuration et de stockage"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: victoriametrics
    group: victoriametrics
    mode: '0755'
  loop:
    - /etc/victoria-metrics
    - /var/lib/victoria-metrics

- name: "VictoriaMetrics : Télécharger et désarchiver le binaire officiel"
  ansible.builtin.unarchive:
    src: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.101.0/victoria-metrics-linux-amd64-v1.101.0.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
    creates: /usr/local/bin/victoria-metrics-prod

- name: "VictoriaMetrics : Générer le fichier de configuration (Prometheus format)"
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/victoria-metrics/prometheus.yml
    owner: victoriametrics
    group: victoriametrics
    mode: '0644'
  notify: "Restart VictoriaMetrics"

- name: "VictoriaMetrics : Installer le fichier de service Systemd"
  ansible.builtin.template:
    src: victoria-metrics.service.j2
    dest: /etc/systemd/system/victoria-metrics.service
    owner: root
    group: root
    mode: '0644'
  notify: "Restart VictoriaMetrics"

- name: "VictoriaMetrics : S'assurer que le service est démarré et activé"
  ansible.builtin.systemd:
    name: victoria-metrics
    enabled: yes
    state: started
    daemon_reload: yes