services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
      - HOST_DATA_DIR=/opt/stacks
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - SKIP_DF_COLLECTION=true
      - COMPOSE_TIMEOUT=3600
    volumes:
      - dockhand_data:/app/data
      - /opt/stacks:/opt/stacks
    networks:
      - proxy_network
      - socket_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockhand.rule=Host(`dockhand.azby.fr`)
      - traefik.http.routers.dockhand.entrypoints=websecure
      - traefik.http.routers.dockhand.tls=true
      - traefik.http.routers.dockhand.tls.certresolver=ovh
      - traefik.http.services.dockhand.loadbalancer.server.port=3000

volumes:
  dockhand_data:

networks:
  proxy_network:
    external: true
  socket_proxy:
    external: true