apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: worker-data-1
  namespace: longhorn
spec:
  allowScheduling: true
  disks:
    default-disk:
      allowScheduling: true
      evictionRequested: false
      path: /var/lib/longhorn
      storageReserved: 0
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: worker-app-1
  namespace: longhorn
spec:
  allowScheduling: true
  disks:
    default-disk:
      allowScheduling: true
      evictionRequested: false
      path: /var/lib/longhorn
      storageReserved: 0