apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 30m
  targetNamespace: longhorn
  chart:
    spec:
      chart: longhorn
      version: "1.12.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
  install:
    disableWait: true
  uninstall:
    disableWait: true
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: false
      systemManagedComponentsNodeSelector: ""
      defaultReplicaCount: 2
      enableTelemetryReporting: false
      guaranteedEngineManagerCPU: "12"
      guaranteedReplicaManagerCPU: "12"
      v2DataEngine: false
      concurrentAutomaticEngineUpgradePerNodeLimit: 0
    csi:
      kubeletRootDir: /var/lib/kubelet
    longhornUI:
      resources:
        limits:
          memory: 128Mi
        requests:
          memory: 32Mi