---
# tasks/adguard.yml

- name: Vérifier la présence du fichier source
  stat:
    path: /opt/stacks/adguard/unbound.conf
  register: source_file

- name: Créer le dossier destination
  file:
    path: /opt/stacks/adguard/unbound
    state: directory
    mode: '0755'
  when: source_file.stat.exists

- name: Mettre à jour le fichier de configuration Unbound
  ansible.builtin.copy:
    src: /opt/stacks/adguard/unbound.conf
    dest: /opt/stacks/adguard/unbound/unbound.conf
    remote_src: true
    mode: '0644'
  when: source_file.stat.exists

- name: Supprimer le fichier source après copie
  ansible.builtin.file:
    path: /opt/stacks/adguard/unbound.conf
    state: absent
  when: source_file.stat.exists

- name: Télécharger le fichier root.hints pour Unbound
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.root
    dest: /opt/stacks/adguard/unbound/root.hints
    mode: '0644'