---
# tasks/victoria-metrics.yml

- name: "[victoria-metrics] Récupérer le hostname et générer le FQDN local"
  ansible.builtin.set_fact:
    current_container_fqdn: >-
      {{ (containers | selectattr('hostname', 'equalto', inventory_hostname) | map(attribute='hostname') | first | default(inventory_hostname)) }}.home

- name: "[victoria-metrics] Initialiser le prometheus.yaml"
  ansible.builtin.copy:
    dest: "{{ target_path }}/prometheus.yaml"
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'node-exporter-lxc'
          static_configs:
            - targets:
      {% for item in containers %}
                - '{{ (item.address.split('/'))[0] }}:9100'
      {% endfor %}

        - job_name: 'cadvisor'
          max_scrape_size: 64MB
          static_configs:
            - targets: ['cadvisor:8080']
    force: true
    mode: '0644'