http:
  serversTransports:
    proxmox-insecure:
      insecureSkipVerify: true

  routers:
    dns-primary:
      rule: "Host(`dns-primary.azby.fr`)"
      entryPoints:
        - "websecure"
      service: "dns-primary-service"
      tls:
        certResolver: "ovh"

    asus-x540la-proxmox:
      rule: "Host(`asus-x540la-proxmox.azby.fr`)"
      entryPoints:
        - "websecure"
      service: "asus-x540la-proxmox-service"
      tls:
        certResolver: "ovh"

    dell-optiplex-proxmox:
      rule: "Host(`dell-optiplex-proxmox.azby.fr`)"
      entryPoints:
        - "websecure"
      service: "dell-optiplex-proxmox-service"
      tls:
        certResolver: "ovh"

    homeassistant:
      rule: "Host(`homeassistant.azby.fr`)"
      entryPoints:
        - "websecure"
      service: "homeassistant-service"
      tls:
        certResolver: "ovh"

    proxmox-backup-server:
      rule: "Host(`proxmox-backup-server.azby.fr`)"
      entryPoints:
        - "websecure"
      service: "proxmox-backup-server-service"
      tls:
        certResolver: "ovh"

  services:
    dns-primary-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.105:5380"

    asus-x540la-proxmox-service:
      loadBalancer:
        serversTransport: "proxmox-insecure@file"
        servers:
          - url: "https://192.168.1.100:8006"

    dell-optiplex-proxmox-service:
      loadBalancer:
        serversTransport: "proxmox-insecure@file"
        servers:
          - url: "https://192.168.1.200:8006"

    homeassistant-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.103:8123"

    proxmox-backup-server-service:
      loadBalancer:
        serversTransport: "proxmox-insecure@file"
        servers:
          - url: "https://192.168.1.101:8007"